name: ai_hw1_13922193

channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.3.0
      - async-timeout==5.0.1
      - backoff==2.2.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - datasets==3.4.1
      - diffusers==0.32.2
      - dill==0.3.8
      - einops==0.8.1
      - evaluate==0.4.3
      - flash-attn==2.7.4.post1
      - fsspec==2024.12.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - lpips==0.1.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multiprocess==0.70.16
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - peft==0.13.2
      - pillow==11.1.0
      - psutil==7.0.0
      - pycparser==2.22
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - rouge-score==0.1.2
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - soundfile==0.13.1
      - sympy==1.13.1
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - transformers==4.48.2
      - triton==3.2.0
      - urllib3==2.3.0
      - xformers==0.0.29.post3
      - xxhash==3.5.0
      - zipp==3.21.0
